require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WordsController, type: :controller do
  let(:word) { "testing" }
  let(:name) { "testing" }
  let(:word_list) { WordList.create!(name: name) }

  # This should return the minimal set of attributes required to create a valid
  # Word. As you add validations to Word, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { word: word } }

  let(:invalid_attributes) { { word: "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #new" do
    it "assigns a new word as @word" do
      get :new, {:word_list_id => word_list}, valid_session
      expect(assigns(:word)).to be_a_new(Word)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Word" do
        expect {
          post :create, {:word_list_id => word_list, :word => valid_attributes}, valid_session
        }.to change(Word, :count).by(1)
      end

      it "assigns a newly created word as @word" do
        post :create, {:word_list_id => word_list, :word => valid_attributes}, valid_session
        expect(assigns(:word)).to be_a(Word)
        expect(assigns(:word)).to be_persisted
      end

      it "redirects to the word_list" do
        post :create, {:word_list_id => word_list, :word => valid_attributes}, valid_session
        expect(response).to redirect_to(word_list)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved word as @word" do
        post :create, {:word_list_id => word_list, :word => invalid_attributes}, valid_session
        expect(assigns(:word)).to be_a_new(Word)
      end

      it "re-renders the 'new' template" do
        post :create, {:word_list_id => word_list, :word => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word" do
      word = Word.create! valid_attributes
      expect {
        delete :destroy, {:word_list_id => word_list, :id => word.to_param}, valid_session
      }.to change(Word, :count).by(-1)
    end

    it "redirects to the word list" do
      word = Word.create! valid_attributes
      delete :destroy, {:word_list_id => word_list, :id => word.to_param}, valid_session
      expect(response).to redirect_to(word_list)
    end
  end

end
